// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.tiandy.model;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string date = 2;</code>
   */
  String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
