// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.tiandy.model;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
