// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.tiandy.model;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ngrpc.proto\"\032\n\013InfoRequest\022\013\n\003msg\030\001 \001(\t" +
      "\"\035\n\014InfoResponse\022\r\n\005infos\030\001 \001(\t\"\034\n\014Greet" +
      "Request\022\014\n\004name\030\001 \001(\t\"*\n\rGreetResponse\022\013" +
      "\n\003msg\030\001 \001(\t\022\014\n\004date\030\002 \001(\t2\231\001\n\014HelloServi" +
      "ce\022\'\n\010GetInfos\022\014.InfoRequest\032\r.InfoRespo" +
      "nse\022+\n\010Greeting\022\r.GreetRequest\032\016.GreetRe" +
      "sponse(\001\0223\n\016GreetingStream\022\r.GreetReques" +
      "t\032\016.GreetResponse(\0010\001B\020\n\005modelB\005HelloP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfoRequest_descriptor,
        new String[] { "Msg", });
    internal_static_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfoResponse_descriptor,
        new String[] { "Infos", });
    internal_static_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreetRequest_descriptor,
        new String[] { "Name", });
    internal_static_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreetResponse_descriptor,
        new String[] { "Msg", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
