// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.tiandy.model;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string infos = 1;</code>
   */
  String getInfos();
  /**
   * <code>string infos = 1;</code>
   */
  com.google.protobuf.ByteString
      getInfosBytes();
}
